version: 2
jobs:
  abas:
    docker:
      - image: cimg/python:3.8

    steps:
    - checkout
    - run: sleep 3s
    - run: ls -a
    - run: ls -a






workflows:
  version: 2
  abas:
    jobs:
    - abas
